# Generated by Django 4.0.2 on 2022-05-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='タグ')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app.Tag', verbose_name='タグ'),
        ),
    ]
