# Generated by Django 4.0.2 on 2022-05-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_tag_tagname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='tagPortfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagPortfolio', to='app.portfolio'),
            preserve_default=False,
        ),
    ]
