# Generated by Django 4.0.2 on 2022-06-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_github_url_profile_twitter_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github_url',
            new_name='githuburl',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter_url',
            new_name='twitterurl',
        ),
    ]
