# Generated by Django 4.0.2 on 2022-07-24 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_github_url_profile_githuburl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='career',
            field=models.CharField(choices=[('1', '1ヶ月未満'), ('2', '1~3ヶ月'), ('3', '3ヶ月~半年'), ('4', '半年~1年'), ('5', '1年~2年'), ('6', '2年以上')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
