# Generated by Django 4.0.2 on 2022-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment_created_on_profile_career_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
